[[NOVAS]]
arch = "aarch64"
git-tree-sha1 = "89c41a03e8cf9e401ac0aa93d5837c93f77f3658"
os = "macos"

    [[NOVAS.download]]
    sha256 = "0ba4fd2f1a2d8f407bfdba62afd20c72be356382089708bbe2fb0f7d024fb436"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.aarch64-apple-darwin.tar.gz"
[[NOVAS]]
arch = "aarch64"
git-tree-sha1 = "c2c9f75a80b9d5528c18b838e5060a271d58b20b"
libc = "glibc"
os = "linux"

    [[NOVAS.download]]
    sha256 = "e634056d8fa1f3e6d37b2215e49a6e353359b8e5b6f7f948acc8431e99ba6afb"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.aarch64-linux-gnu.tar.gz"
[[NOVAS]]
arch = "aarch64"
git-tree-sha1 = "4b216f91a516a13bdb363e0ff020fc90513baca5"
libc = "musl"
os = "linux"

    [[NOVAS.download]]
    sha256 = "68c3acecc9d1d106d73e7c8e19db155cdb77eeff8e1231e8eac05454fae6a6c0"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.aarch64-linux-musl.tar.gz"
[[NOVAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ff1d38e7da78ac4cd15161b0423762de4322b1b"
libc = "glibc"
os = "linux"

    [[NOVAS.download]]
    sha256 = "baaf4011c654caf0b5c345e7430d2f62ce05b04da57e60c2fed171a5f593f833"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.armv6l-linux-gnueabihf.tar.gz"
[[NOVAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3244c2dd9a6d9797d0f3762d3206691dee8f4f1a"
libc = "musl"
os = "linux"

    [[NOVAS.download]]
    sha256 = "b502c4015dfc96b57feb718d04d3115b623d8e938c4f0f3fd23d1f002c296a2c"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.armv6l-linux-musleabihf.tar.gz"
[[NOVAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "71f6e90c2a3cc22a29f69622f6d4f2e0c24f7862"
libc = "glibc"
os = "linux"

    [[NOVAS.download]]
    sha256 = "37f6edfe7813554364d9547cdf7fe2272e17ea2534bf140f0e4012e82378ff39"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.armv7l-linux-gnueabihf.tar.gz"
[[NOVAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1c8db719c89a80879d6b8552f35982a854931433"
libc = "musl"
os = "linux"

    [[NOVAS.download]]
    sha256 = "cbd5ef938c26ccee0f52f366e71435f5a9185847d8765469f035f62d77e11ab2"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.armv7l-linux-musleabihf.tar.gz"
[[NOVAS]]
arch = "i686"
git-tree-sha1 = "2023f9507c80f9c8d48d6d7601d694782404ac44"
libc = "glibc"
os = "linux"

    [[NOVAS.download]]
    sha256 = "3334be218801da3d5e19dcd466226f44f35975446977b26f3ba1b400cb07b39e"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.i686-linux-gnu.tar.gz"
[[NOVAS]]
arch = "i686"
git-tree-sha1 = "40c6d455e7605a5ea8112cdefbb334ef350a9735"
libc = "musl"
os = "linux"

    [[NOVAS.download]]
    sha256 = "d8b73c8a8db05979d917901aa3320ec1fa18b898a49291754dbda5529f97d82e"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.i686-linux-musl.tar.gz"
[[NOVAS]]
arch = "i686"
git-tree-sha1 = "e695505a7959b62395ea6d8736708734b7a716e2"
os = "windows"

    [[NOVAS.download]]
    sha256 = "664da293fb8bc2364d7d769d9342fa6096299f2f34ee11fb5060247b3c8c1e50"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.i686-w64-mingw32.tar.gz"
[[NOVAS]]
arch = "powerpc64le"
git-tree-sha1 = "665774bd7a0516ac6e1a107d383707d3b9f192c3"
libc = "glibc"
os = "linux"

    [[NOVAS.download]]
    sha256 = "91b677efad07a8982551dc231253198a6499cee70c908239f69ea75cab2f5493"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.powerpc64le-linux-gnu.tar.gz"
[[NOVAS]]
arch = "x86_64"
git-tree-sha1 = "4381d6914954208930008aa2b9e93c8fa5a3e047"
os = "macos"

    [[NOVAS.download]]
    sha256 = "9e3bdc253830e2e57b4cc3685363e3d8c137e21c3c9b4f18103564e7efa80790"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.x86_64-apple-darwin.tar.gz"
[[NOVAS]]
arch = "x86_64"
git-tree-sha1 = "2fd5fcc90eacb7bfcafec9b6571160cf64c8b004"
libc = "glibc"
os = "linux"

    [[NOVAS.download]]
    sha256 = "5b94f129ea1eb9276bc9a6d2b6c67ec42d78921055f570d3c631fb08efe586c4"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.x86_64-linux-gnu.tar.gz"
[[NOVAS]]
arch = "x86_64"
git-tree-sha1 = "cd259f3390f1fcb0142fadf38dba870a7f3af522"
libc = "musl"
os = "linux"

    [[NOVAS.download]]
    sha256 = "1959b39ac60074a8178d33476d6cda3ce4fa0fb14cdc2a399195a9ec5a1dfade"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.x86_64-linux-musl.tar.gz"
[[NOVAS]]
arch = "x86_64"
git-tree-sha1 = "ceccbbc7820ecd9d88278f337c74fc3d679c5d6f"
os = "freebsd"

    [[NOVAS.download]]
    sha256 = "e579028261a7775225f2e7e48194402b8089e9f0bcc163fc03873c7b99aa1e0b"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.x86_64-unknown-freebsd.tar.gz"
[[NOVAS]]
arch = "x86_64"
git-tree-sha1 = "0e4b32b788c8e9a47d3d826f3d705392ba2d98e0"
os = "windows"

    [[NOVAS.download]]
    sha256 = "b173820474e306ec39683c20338cc60e21848f5f4c95236b2880c7ce219a1326"
    url = "https://github.com/JuliaBinaryWrappers/NOVAS_jll.jl/releases/download/NOVAS-v3.1.0+1/NOVAS.v3.1.0.x86_64-w64-mingw32.tar.gz"
